"""update surat 2

Revision ID: 5bd4511f7c58
Revises: c6dde531f332
Create Date: 2025-06-16 15:04:06.689898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5bd4511f7c58'
down_revision: Union[str, None] = 'c6dde531f332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surat_keluar', sa.Column('tanggal_surat', sa.DateTime(), nullable=False))
    op.add_column('surat_keluar', sa.Column('tanggal_kirim', sa.DateTime(), nullable=False))
    op.add_column('surat_keluar', sa.Column('inserted_by_id', sa.Integer(), nullable=False))
    op.add_column('surat_keluar', sa.Column('array_id_dibaca_oleh', sa.ARRAY(sa.Integer()), nullable=True))
    op.alter_column('surat_keluar', 'inserted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_foreign_key(None, 'surat_keluar', 'users', ['inserted_by_id'], ['id'])
    op.drop_column('surat_keluar', 'tanggal_surat_keluar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surat_keluar', sa.Column('tanggal_surat_keluar', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'surat_keluar', type_='foreignkey')
    op.alter_column('surat_keluar', 'inserted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('surat_keluar', 'array_id_dibaca_oleh')
    op.drop_column('surat_keluar', 'inserted_by_id')
    op.drop_column('surat_keluar', 'tanggal_kirim')
    op.drop_column('surat_keluar', 'tanggal_surat')
    # ### end Alembic commands ###
