"""update template surat

Revision ID: 5f3992d99d95
Revises: 9381824ff11b
Create Date: 2025-06-17 11:30:30.880065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f3992d99d95'
down_revision: Union[str, None] = '9381824ff11b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_surat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_template', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('inserted_by_id', sa.Integer(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inserted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_surat_id'), 'template_surat', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_surat_id'), table_name='template_surat')
    op.drop_table('template_surat')
    # ### end Alembic commands ###
