"""revisi database

Revision ID: 674188203cb4
Revises: 
Create Date: 2025-06-15 18:50:37.362195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674188203cb4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surat_keluar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomor_surat', sa.String(), nullable=False),
    sa.Column('tanggal_surat_keluar', sa.DateTime(), nullable=False),
    sa.Column('perihal', sa.String(), nullable=False),
    sa.Column('ditujukan_kepada', sa.String(), nullable=False),
    sa.Column('keterangan', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surat_keluar_id'), 'surat_keluar', ['id'], unique=False)
    op.create_table('surat_masuk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomor_surat', sa.String(), nullable=False),
    sa.Column('tanggal_surat_diterima', sa.DateTime(), nullable=False),
    sa.Column('perihal', sa.String(), nullable=False),
    sa.Column('ditujukan_kepada', sa.String(), nullable=False),
    sa.Column('keterangan', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surat_masuk_id'), 'surat_masuk', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('nama_lengkap', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('sekertaris', 'kasub', 'staf', name='roleenum'), nullable=True),
    sa.Column('divisi', sa.Enum('teknis_dan_hukum', 'data_dan_informasi', 'logistik_dan_keuangan', 'sdm_dan_parmas', name='divisienum'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_surat_masuk_id'), table_name='surat_masuk')
    op.drop_table('surat_masuk')
    op.drop_index(op.f('ix_surat_keluar_id'), table_name='surat_keluar')
    op.drop_table('surat_keluar')
    # ### end Alembic commands ###
