"""update tables

Revision ID: 6d773942c4de
Revises: 06887e90bea9
Create Date: 2025-06-24 00:10:02.788462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d773942c4de'
down_revision: Union[str, None] = '06887e90bea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surat_keluar_dibaca_oleh',
    sa.Column('surat_keluar_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['surat_keluar_id'], ['surat_keluar.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('surat_keluar_id', 'user_id')
    )
    op.create_table('surat_masuk_dibaca_oleh',
    sa.Column('surat_masuk_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['surat_masuk_id'], ['surat_masuk.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('surat_masuk_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surat_masuk_dibaca_oleh')
    op.drop_table('surat_keluar_dibaca_oleh')
    # ### end Alembic commands ###
