"""update atribut divis surat

Revision ID: 77de3f26ef70
Revises: 5f3992d99d95
Create Date: 2025-06-23 10:26:03.530616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77de3f26ef70'
down_revision: Union[str, None] = '5f3992d99d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surat_keluar', sa.Column('divisi', sa.Enum('teknis_dan_hukum', 'data_dan_informasi', 'logistik_dan_keuangan', 'sdm_dan_parmas', name='divisienum'), nullable=False))
    op.add_column('surat_masuk', sa.Column('divisi', sa.Enum('teknis_dan_hukum', 'data_dan_informasi', 'logistik_dan_keuangan', 'sdm_dan_parmas', name='divisienum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surat_masuk', 'divisi')
    op.drop_column('surat_keluar', 'divisi')
    # ### end Alembic commands ###
