"""update surat 4

Revision ID: 9381824ff11b
Revises: b0dc107f6ce1
Create Date: 2025-06-16 15:24:21.105972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9381824ff11b'
down_revision: Union[str, None] = 'b0dc107f6ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surat_keluar_dibaca_oleh',
    sa.Column('surat_keluar_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['surat_keluar_id'], ['surat_keluar.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('surat_keluar_id', 'user_id')
    )
    op.create_table('surat_masuk_dibaca_oleh',
    sa.Column('surat_masuk_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['surat_masuk_id'], ['surat_masuk.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('surat_masuk_id', 'user_id')
    )
    op.drop_column('surat_keluar', 'array_id_dibaca_oleh')
    op.drop_column('surat_masuk', 'array_id_dibaca_oleh')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surat_masuk', sa.Column('array_id_dibaca_oleh', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('surat_keluar', sa.Column('array_id_dibaca_oleh', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_table('surat_masuk_dibaca_oleh')
    op.drop_table('surat_keluar_dibaca_oleh')
    # ### end Alembic commands ###
