"""update surat  database

Revision ID: c6dde531f332
Revises: 674188203cb4
Create Date: 2025-06-16 15:00:16.430578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6dde531f332'
down_revision: Union[str, None] = '674188203cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surat_masuk', sa.Column('tanggal_surat', sa.DateTime(), nullable=False))
    op.add_column('surat_masuk', sa.Column('tanggal_terima', sa.DateTime(), nullable=False))
    op.add_column('surat_masuk', sa.Column('pengirim', sa.String(), nullable=False))
    op.add_column('surat_masuk', sa.Column('inserted_by_id', sa.Integer(), nullable=False))
    op.add_column('surat_masuk', sa.Column('array_id_dibaca_oleh', sa.ARRAY(sa.Integer()), nullable=True))
    op.create_foreign_key(None, 'surat_masuk', 'users', ['inserted_by_id'], ['id'])
    op.drop_column('surat_masuk', 'tanggal_surat_diterima')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surat_masuk', sa.Column('tanggal_surat_diterima', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'surat_masuk', type_='foreignkey')
    op.drop_column('surat_masuk', 'array_id_dibaca_oleh')
    op.drop_column('surat_masuk', 'inserted_by_id')
    op.drop_column('surat_masuk', 'pengirim')
    op.drop_column('surat_masuk', 'tanggal_terima')
    op.drop_column('surat_masuk', 'tanggal_surat')
    # ### end Alembic commands ###
