"""update array dibaca oleh

Revision ID: e650881aa952
Revises: 77de3f26ef70
Create Date: 2025-06-23 10:48:29.870539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e650881aa952'
down_revision: Union[str, None] = '77de3f26ef70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surat_keluar', sa.Column('dibaca_oleh_id', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('surat_masuk', sa.Column('dibaca_oleh_id', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surat_masuk', 'dibaca_oleh_id')
    op.drop_column('surat_keluar', 'dibaca_oleh_id')
    # ### end Alembic commands ###
